# -*- coding: utf-8 -*-
"""Análise descritiva

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duI8zLKb8_iH47zzWUSaCqnAbyC1pSK5
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind

df = pd.read_csv('base_alunos.csv')

df_interesse = df[['Nota_Teste', 'TipoEsc']]

desc_stats = df_interesse.groupby('TipoEsc')['Nota_Teste'].describe()
print(desc_stats)

"""Análise Descritiva das Notas por Tipo de Escola
A análise descritiva das notas, segmentada por tipo de escola, revela que:

Para escolas privadas, a média das notas é 7.78, com um desvio padrão de 1.36.
Para escolas públicas, a média das notas é 4.69, com um desvio padrão de 2.31.
"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='TipoEsc', y='Nota_Teste', data=df_interesse)
plt.title('Box Plot das Notas por Tipo de Escola')
plt.xlabel('Tipo de Escola')
plt.ylabel('Nota do Teste')
plt.show()

notas_escola_publica = df_interesse[df_interesse['TipoEsc'] == 'Pub']['Nota_Teste']
notas_escola_privada = df_interesse[df_interesse['TipoEsc'] == 'Priv']['Nota_Teste']

t_stat, p_value = ttest_ind(notas_escola_publica, notas_escola_privada)
print(f'Estatística t: {t_stat}, Valor p: {p_value}')

import pandas as pd

df = pd.read_csv('base_alunos.csv')
df_interesse = df[['Nota_Teste', 'TipoEsc']].rename(columns={'Nota_Teste': 'nota_teste', 'TipoEsc': 'tipoesc'})

df_interesse.dropna(subset=['nota_teste', 'tipoesc'], inplace=True)

df_interesse.to_csv('base_alunos_interesse.csv', index=False)

print("Arquivo exportado com sucesso!")

python exportar_dados.py

"""### Análise Descritiva das Notas por Tipo de Escola

A análise descritiva das notas, segmentada por tipo de escola, revela que:

- **Escolas Privadas:**
  - Média: 7.78
  - Desvio Padrão: 1.36
  - Nota Mínima: 3.0
  - Primeiro Quartil (25%): 7.0
  - Mediana (50%): 8.0
  - Terceiro Quartil (75%): 8.625
  - Nota Máxima: 10.0

- **Escolas Públicas:**
  - Média: 4.69
  - Desvio Padrão: 2.31
  - Nota Mínima: 1.5
  - Primeiro Quartil (25%): 2.625
  - Mediana (50%): 4.5
  - Terceiro Quartil (75%): 6.75
  - Nota Máxima: 9.0

### Análise dos Resultados do Teste T

O teste T foi realizado para comparar as médias das notas entre os tipos de escola. Os resultados obtidos foram:

- Estatística t: -5.3488
- Valor p: 3.347e-06

### Interpretação

O valor p é significativamente menor que 0.05, o que nos permite rejeitar a hipótese nula de que não há diferença nas médias das notas entre escolas públicas e privadas. Portanto, podemos concluir que há uma diferença estatisticamente significativa nas médias das notas entre alunos de escolas públicas e privadas.
"""